version: '3'

services:
  # MySQL
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: coffee_dog
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
  backend:
    build: backend
    container_name: backend
    ports:
      - 1323:1323
    depends_on:
      - "db"
